# Generated by Django 4.0.6 on 2022-09-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-user']},
        ),
    ]
